Flight/Flight/urls.py
from django.contrib import admin
from django.urls import path,include
from userapp.views import *
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('userapp/',include('userapp.urls',namespace="userapp"))
]

Flight/userapp/forms.py
from django import forms
from .models import *
from django.forms.widgets import DateInput
# Create your forms here.
class UserForm(forms.Form):
       name=forms.CharField(label="Enter your name")
       email=forms.CharField(label="Enter Email")
       comment=forms.CharField(label="Type your comment")
       
class msgForm(forms.Form):
       fromemail=forms.CharField(label="Enter from email")
       toemail=forms.CharField(label="Enter destination Email")
       message=forms.CharField(label="Type in your message")

class user_form(forms.Form):
    name=forms.CharField(label="enter your names") 
    email=forms.EmailField(label="enter user email")
    phone=forms.IntegerField(label="enter phone number")
    message=forms.CharField(label="enter your message")    
    
class Messageform(forms.ModelForm):
    class Meta:
        model = Message
        fields="__all__"
        
class UserFeedbackform(forms.ModelForm):
     class Meta:
         model=Userfeedback
         fields="__all__"         
         
class CreateTravelRouteForm(forms.ModelForm):         
      class Meta:
          model=TravelRoutes
          fields="__all__"
      
class Reservationform(forms.ModelForm):
       class Meta:
           model=Reservation
           fields="__all__"
class Reservationform_oneway(forms.ModelForm):
       reserveId=forms.CharField(label="",widget=forms.HiddenInput())
       class Meta:
           model=Reservation_oneway
           fields="__all__"
class Reservationform_return(forms.ModelForm):
       reserveId=forms.CharField(label="",widget=forms.HiddenInput())
       class Meta:
           model=Reservation_return
           fields="__all__"

class MakeRouteform(forms.ModelForm):
       class Meta:
           model=MakeRoute
           fields="__all__"
class MakeReservation_2form(forms.Form):       
       Origin=forms.ModelChoiceField(label="From:",queryset=MakeRoute.objects.all())
       Destination=forms.ModelChoiceField(label="To:",queryset=MakeRoute.objects.all())  
       triptTypeOptions=[("oneway","One Way"),("return","RETURN")]
       TripType=forms.ChoiceField(label="",choices=triptTypeOptions,widget=forms.RadioSelect())
              
class MakeReservation_3form(forms.Form):       
       Going=forms.DateField(label="Going on:",widget=forms.widgets.DateInput(attrs={'type':'date'}))

class MakeReservation_oneway_form(forms.ModelForm):       
        goingDate=forms.DateField(label="Going on:",widget=forms.widgets.DateInput(attrs={'type':'date'}))
        class Meta:
           model=ReserveForm_oneway
           fields="__all__"       
class MakeReservation_return_form(forms.ModelForm):       
        goingDate=forms.DateField(label="Going on:",widget=forms.widgets.DateInput(attrs={'type':'date'}))
        returnDate=forms.DateField(label="Return on:",widget=forms.widgets.DateInput(attrs={'type':'date'}))
        class Meta:
           model=ReserveForm_return
           fields="__all__"     
             
class MakeReservation_4form(forms.Form):       
       Going=forms.DateField(label="Going on:",widget=forms.widgets.DateInput(attrs={'type':'date'}))
       Return=forms.DateField(label="Coming Back on:",widget=forms.widgets.DateInput(attrs={'type':'date'}))       
class MakeReservation_4formBKUP(forms.Form):       
       Origin=forms.ModelChoiceField(label="From:",queryset=MakeRoute.objects.all())
       Destination=forms.ModelChoiceField(label="To:",queryset=MakeRoute.objects.all())  
       triptTypeOptions=[("oneway","One Way"),("return","RETURN")]
       TripType=forms.ChoiceField(label="",choices=triptTypeOptions,widget=forms.RadioSelect())
       Going=forms.DateField(label="Going on:",widget=forms.widgets.DateInput(attrs={'type':'date'}))
       Return=forms.DateField(label="Coming Back on:",widget=forms.widgets.DateInput(attrs={'type':'date'}))       

Flight/templates/blankform.html
<b>{{formtitle}} </b>
<form action="" method="post">
{{df.as_ul}}

<input type="submit" value="{{buttontext}}">

</form>

Flight/templates/contact.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    	<title>Flight - Contact Page</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/fontAwesome.css' %}">
        <link rel="stylesheet" href="{% static 'css/hero-slider.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl-carousel.css' %}">
        <link rel="stylesheet" href="{% static 'css/tooplate-style.css' %}">

        <link href="https://fonts.googleapis.com/css?family=Spectral:200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">

        <script src="js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>
    </head>

<body>


    <section class="page-heading" id="top">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="logo">
                        <img src="{% static 'img/logo.png' %}" alt="Flight Template">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="page-direction-button">
                        <a href="/userapp/index"><i class="fa fa-home"></i>Go Back Home</a>
                    </div>
                </div>
            </div>
        </div>
    </section>



    <section class="contact-us">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-heading">
                        <h2>Contact Information</h2>
                        <p>At Flight we offer one of the best and affordable airline booking.</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <img src="{% static 'img/contact-01.jpg' %}" alt="">
                </div>
                <div class="col-md-6">
                    <img src="{% static 'img/contact-02.jpg' %}" alt="">
                </div>
                
                
                <div class="col-md-4">
                    <h6>You can contact Us For Any Questions</h6>
                    <p>Put in your details to enable us send in a reply.</p>
                </div>
            </div>
        </div>
    </section>



    <section class="contact-form">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-heading">
                        <h2>Leave us a message</h2>
                    </div>
                </div>
                <div class="col-md-6 col-md-offset-3">
                    <form id="contact" action="#" method="post">
                        <div class="row">
                            <div class="col-md-6">
                                <fieldset>
                                    <input name="name" type="text" class="form-control" id="name" placeholder="Your name..." required="">
                                </fieldset>
                            </div>
                            <div class="col-md-6">
                                <fieldset>
                                    <input name="email" type="text" class="form-control" id="email" placeholder="Your email..." required="">
                                </fieldset>
                            </div>
                            <div class="col-md-12">
                                <fieldset>
                                    <textarea name="message" rows="6" class="form-control" id="message" placeholder="Your message..." required=""></textarea>
                                </fieldset>
                            </div>
                            <div class="col-md-12">
                                <fieldset>
                                    <button type="submit" id="form-submit" class="btn">Submit Your Message</button>
                                </fieldset>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>



    



    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="primary-button">
                        <a href="#" class="scroll-top">Back To Top</a>
                    </div>
                </div>
                <div class="col-md-12">
                    <ul class="social-icons">
                        <li><a href="https://www.facebook.com/tooplate"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="#"><i class="fa fa-rss"></i></a></li>
                        <li><a href="#"><i class="fa fa-behance"></i></a></li>
                    </ul>
                </div>
                <div class="col-md-12">
                    <p>Copyright &copy; 2018 Flight Tour and Travel Company
                
                | Design: <a href="http://www.tooplate.com/view/2093-flight" target="_parent"><em>Flight</em></a></p>
                </div>
            </div>
        </div>
    </footer>


    


    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

    <script src="js/vendor/bootstrap.min.js"></script>

    <script src="js/plugins.js"></script>
    <script src="js/main.js"></script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript">
    $(document).ready(function() {
        // navigation click actions 
        $('.scroll-link').on('click', function(event){
            event.preventDefault();
            var sectionID = $(this).attr("data-id");
            scrollToID('#' + sectionID, 750);
        });
        // scroll to top action
        $('.scroll-top').on('click', function(event) {
            event.preventDefault();
            $('html, body').animate({scrollTop:0}, 'slow');         
        });
        // mobile nav toggle
        $('#nav-toggle').on('click', function (event) {
            event.preventDefault();
            $('#main-nav').toggleClass("open");
        });
    });
    // scroll function
    function scrollToID(id, speed){
        var offSet = 0;
        var targetOffset = $(id).offset().top - offSet;
        var mainNav = $('#main-nav');
        $('html,body').animate({scrollTop:targetOffset}, speed);
        if (mainNav.hasClass("open")) {
            mainNav.css("height", "1px").removeClass("in").addClass("collapse");
            mainNav.removeClass("open");
        }
    }
    if (typeof console === "undefined") {
        console = {
            log: function() { }
        };
    }
    </script>
</body>
</html>

Flight/templates/forms.html
{%extends 'index_2.html' %}

{%block content%}
<style>
.formsgroup{padding:25px;text-align:center;}
.formsgroup  input{padding:11px;display:inline-block;width:60%;
border:solid 1px lightblue;}
.formsgroup  select{padding:11px;display:inline-block;width:60%;
border:solid 1px lightblue;}
.details{color:lightgray;font-size:20px;}
</style>

<div class="details">
Trip Type :{{triptype}}
Return Date :{{goingdate}}
Origin:{{origin}}
Destination :{{destination}}
TranCode: {{trscode}}
</div>
<form method="POST"  class="formsgroup">
{% csrf_token %}
{{forms.as_p}}
<input type="submit" value="submit form">

</form>

{%endblock%}

Flight/templates/index_signup.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    	<title>Flight - Travel and Tour</title>
    
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/fontAwesome.css' %}">
        <link rel="stylesheet" href="{% static 'css/hero-slider.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl-carousel.css' %}">
        <link rel="stylesheet" href="{% static 'css/datepicker.css' %}">
        <link rel="stylesheet" href="{% static 'css/tooplate-style.css' %}">

        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">

        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
    </head>

<body>

    
    <section class="banner" id="top">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <div class="left-side">
                        <div class="logo">
                            <img src="{% static 'img/logo.png' %}" >
                        </div>
                      
                </div>
                <div class="col-md-5 col-md-offset-1">
                    <section id="first-tab-group" class="tabgroup">
                        <div id="tab1">
                            
                                {%block content%}
	  
	  
	  
	  {%endblock%}
                               
                            
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </section>


      <div>
	  
	  </div>



    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="primary-button">
                        <a href="#" class="scroll-top">Back To Top</a>
                    </div>
                </div>
                <div class="col-md-12">
                    <ul class="social-icons">
                        <li><a href="https://www.facebook.com/tooplate"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="#"><i class="fa fa-rss"></i></a></li>
                        <li><a href="#"><i class="fa fa-behance"></i></a></li>
                    </ul>
                </div>
                <div class="col-md-12">
                    
                
                | Design: <a href="http://www.tooplate.com/view/2093-flight" target="_parent"><em></em></a></p>
                </div>
            </div>
        </div>
    </footer>


    


    <script src="{% static '//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js' %}"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

    <script src="js/vendor/bootstrap.min.js"></script>
    
    <script src="js/datepicker.js"></script>
    <script src="js/plugins.js"></script>
    <script src="js/main.js"></script>

    <script src="{% static 'http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
    $(document).ready(function() {

        

        // navigation click actions 
        $('.scroll-link').on('click', function(event){
            event.preventDefault();
            var sectionID = $(this).attr("data-id");
            scrollToID('#' + sectionID, 750);
        });
        // scroll to top action
        $('.scroll-top').on('click', function(event) {
            event.preventDefault();
            $('html, body').animate({scrollTop:0}, 'slow');         
        });
        // mobile nav toggle
        $('#nav-toggle').on('click', function (event) {
            event.preventDefault();
            $('#main-nav').toggleClass("open");
        });
    });
    // scroll function
    function scrollToID(id, speed){
        var offSet = 0;
        var targetOffset = $(id).offset().top - offSet;
        var mainNav = $('#main-nav');
        $('html,body').animate({scrollTop:targetOffset}, speed);
        if (mainNav.hasClass("open")) {
            mainNav.css("height", "1px").removeClass("in").addClass("collapse");
            mainNav.removeClass("open");
        }
    }
    if (typeof console === "undefined") {
        console = {
            log: function() { }
        };
    }
    </script>
</body>
</html>

Flight/templates/reservationhome.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    	<title>Flight - Travel and Tour -homepage</title>
    
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/fontAwesome.css' %}">
        <link rel="stylesheet" href="{% static 'css/hero-slider.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl-carousel.css' %}">
        <link rel="stylesheet" href="{% static 'css/datepicker.css' %}">
        <link rel="stylesheet" href="{% static 'css/tooplate-style.css' %}">

        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">

        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
    </head>

<body>
<section class="banner" id="top">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <div class="left-side">
                        <div class="logo">
                            <img src="{% static 'img/logo.png' %}" >
                        </div>
                        <div class="tabs-content">
                            <h4>Choose Your Direction:</h4>
                            <ul class="social-links">
                                <li><a href="http://facebook.com">Find us on <em>Facebook</em><i class="fa fa-facebook"></i></a></li>
                                <li><a href="http://youtube.com">Our <em>YouTube</em> Channel<i class="fa fa-youtube"></i></a></li>
                                <li><a href="http://instagram.com">Follow our <em>instagram</em><i class="fa fa-instagram"></i></a></li>
                            </ul>
                        </div>
                        <div class="page-direction-button">
                            <a href="/userapp/contact"><i class="fa fa-phone"></i>Contact Us Now</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-5 col-md-offset-1">
                    <section id="first-tab-group" class="tabgroup">
                        <div id="tab1">
                            <div class="submit-form">
                                <h4>Check availability for <em>direction</em>:</h4>
								
								<style>
								#id_TripType{display:inline-block;width:80%;margin:11px;}
								</style>
								
                                <form id="form-submit"  method="POST">
								{%csrf_token%}
                                    <div class="row">
                                        <div class="col-md-12">
                                            {{forms.as_p}}
                                        </div>
                                        
                                        <div class="col-md-12">
                                            <fieldset>
                                                <input type="submit" id="form-submit" class="btn" value='Order Ticket Now' />
                                            </fieldset>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </section>



    <div class="tabs-content" id="weather">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-heading">
                        <h2>Check Weather For 5 NEXT Days<p>
						
						</h2>
                    </div>
                </div>
                <div class="wrapper">
                    <div class="col-md-12">
                        <div class="weather-content">
                            <div class="row">
                                <div class="col-md-12">
                                    <ul class="tabs clearfix" data-tabgroup="second-tab-group">
                                        <li><a href="#monday" class="active">Monday</a></li>
                                        <li><a href="#tuesday">Tuesday</a></li>
                                        <li><a href="#wednesday">Wednesday</a></li>
                                        <li><a href="#thursday">Thursday</a></li>
                                        <li><a href="#friday">Friday</a></li>
                                    </ul>    
                                </div>
								
					 </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>









    <div class="tabs-content" id="weather">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-heading">
                        <h2>
						
						
						{%block content%}
						
						
						{%endblock%}
						
						</h2>
                    </div>
                </div>
           
            </div>
        </div>
    </div>























    <section class="services">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="service-item first-service">
                        <div class="service-icon"></div>
                        <h4>Easy Tooplate</h4>
                        <p>Donec varius porttitor iaculis. Integer sollicitudin erat et ligula viverra vulputate. In in quam efficitur, pulvinar justo ut, tempor nunc. Phasellus pharetra quis odio.</p>
                        </a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="service-item second-service">
                        <div class="service-icon"></div>
                        <h4>Unique Ideas</h4>
                        <p>Cras ligula diam, tristique at aliquam at, fermentum auctor turpis. Proin leo massa, iaculis elementum massa et, consectetur varius dolor. Fusce sed ipsum sit.</p>
                        </a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="service-item third-service">
                        <div class="service-icon"></div>
                        <h4>Best Support</h4>
                        <p>Fusce leo dui. Mauris et justo eget arcu ultricies porta. Nulla facilisi. Nulla nec risus sit amet magna hendrerit venenatis. Sed porta tincidunt lectus eget ultrices.</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section id="most-visited">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="section-heading">
                        <h2>Most Visited Places</h2>
                    </div>
                </div>
                <div class="col-md-12">
                    <div id="owl-mostvisited" class="owl-carousel owl-theme">
                        
                       
                    </div>
                </div>
            </div>
        </div>
    </section>



    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="primary-button">
                        <a href="#" class="scroll-top">Back To Top</a>
                    </div>
                </div>
                <div class="col-md-12">
                    <ul class="social-icons">
                        <li><a href="https://www.facebook.com/tooplate"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="#"><i class="fa fa-rss"></i></a></li>
                        <li><a href="#"><i class="fa fa-behance"></i></a></li>
                    </ul>
                </div>
                <div class="col-md-12">
                    <p>Copyright &copy; 2018 Flight Tour and Travel Company
                
                | Design: <a href="http://www.tooplate.com/view/2093-flight" target="_parent"><em>Flight</em></a></p>
                </div>
            </div>
        </div>
    </footer>




    <script src="{% static '//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js' %}"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    
    <script src="{% static 'js/datepicker.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript">
    $(document).ready(function() {

        

        // navigation click actions 
        $('.scroll-link').on('click', function(event){
            event.preventDefault();
            var sectionID = $(this).attr("data-id");
            scrollToID('#' + sectionID, 750);
        });
        // scroll to top action
        $('.scroll-top').on('click', function(event) {
            event.preventDefault();
            $('html, body').animate({scrollTop:0}, 'slow');         
        });
        // mobile nav toggle
        $('#nav-toggle').on('click', function (event) {
            event.preventDefault();
            $('#main-nav').toggleClass("open");
        });
    });
    // scroll function
    function scrollToID(id, speed){
        var offSet = 0;
        var targetOffset = $(id).offset().top - offSet;
        var mainNav = $('#main-nav');
        $('html,body').animate({scrollTop:targetOffset}, speed);
        if (mainNav.hasClass("open")) {
            mainNav.css("height", "1px").removeClass("in").addClass("collapse");
            mainNav.removeClass("open");
        }
    }
    if (typeof console === "undefined") {
        console = {
            log: function() { }
        };
    }
    </script>
</body>
</html>

Flight/templates/user_feedback.html
<style>
 p{
    color: green;
	border: solid 50px;
	 }
</style>
{% extends 'index.html'%}
{%load static%}

{%block content%}
<b>User feedback</b>
<p>
{%for x in allfeedback%}
<p>{{x.names}} &nbsp; {{x.email}}</p>
{%endfor%}
{%endblock%}

Flight/templates/usermessage.html
{%extends 'index.html' %}

{%block content%}
<style>
.main form{padding:20px;border:solid 1px green;margin 5px;width:600px;display:inline-block;}

.main label{width:90%;padding:5px;margin:5px;display:inline-block;text-align:center;font-weight:bolder;border:solid 1px lightgray}
.main input{width:90%;padding:5px;margin:5px;display:inline-block;text-align:center;font-weight:bolder;border:solid 1px lightgray}

</style>

<div class= "main">
<form method="POST">
{% csrf_token %}
{{forms.as_table}}
<input type="submit" value="submit form">

</form>
</div>

{%endblock%}

Flight/templates/viewallroutes.html
{%extends 'index_2.html' %}

{%block content%}
<style>
.formsgroup{padding:25px;text-align:center;}

.show{padding:11px;display:inline-block;width:80%;
border:solid 1px lightblue;margin:20px;}
</style>

{%for route in routes%}
<div class="show">{{route.airline}} &nbsp;  {{route.travelroute}}
&nbsp;
{{route.routefee}}
</div>
{%endfor%}
{%endblock%}

Flight/templates/viewreserve.html
{%extends 'index_2.html' %}

{%block content%}
<style>
.formsgroup{padding:25px;text-align:center;}
.formsgroup  input{padding:11px;display:inline-block;width:60%;
border:solid 1px lightblue;}
.formsgroup  select{padding:11px;display:inline-block;width:60%;
border:solid 1px lightblue;}
.details{color:lightgray;font-size:20px;}
.details_2{color:blue;font-size:18px;}
.detailx{color:blue;font-size:18px;display:inline-block;padding:10px;width:auto;}
.paybutton{background:blue;text:white;width:140px;padding:5px;text-align:center;padding-top:10px;height:150px;
color:#fff;
}
</style>

<div class="details">
Reservation  Details
</div>


<div class="details_2">
{{details.reserveId}}


<p>
<span class="detailx">  {{details.email}} </span>
<span class="detailx">{{details.phone}}</span>
</p>
{{details.Trip}}  {{details.options}} | {{details.goingdate}}

<button class="paybutton" >PAYMENT </button>
<span style="clear:both;"></span>
</div>

<script>


</script>


{%endblock%}